name: Experiment
on: 
  schedule:
  - cron: '*/5 * * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      shell: bash
      run: |
        echo "Hello World!"
