---
name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      locale_mx:
        description: "The locales to run tests"
        default: '["jp","cn"]'

jobs:	  
  greet:
    strategy:
      matrix:
        locale_mx: ${{ fromJSON(github.event.inputs.locale_mx) }}
    uses: ./.github/workflows/workflow-b.yaml
    with:
      config-path: ${{ matrix.locale_mx }}
