---
name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      env_variables:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Echo outputs from last job
        shell: bash
        run: |
          echo ${{ inputs.config-path }}
          echo ${{ inputs.env_variables }}
